<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../Biriani_Registry.php';

/**
 * Test class for Biriani_Registry.
 * Generated by PHPUnit on 2012-02-04 at 04:23:33.
 */
class Biriani_RegistryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Biriani_Registry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Biriani_Registry;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
