<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../Biriani_Response.php';

/**
 * Test class for Biriani_Response.
 * Generated by PHPUnit on 2012-02-04 at 04:33:42.
 */
class Biriani_ResponseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Biriani_Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Biriani_Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGet_status_code().
     */
    public function testGet_status_code() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSet_content().
     */
    public function testSet_content() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
