<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../Biriani_Extractable_Abstract.php';

/**
 * Test class for Biriani_Extractable_Abstract.
 * Generated by PHPUnit on 2012-02-04 at 04:36:52.
 */
class Biriani_Extractable_AbstractTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Biriani_Extractable_Abstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Biriani_Extractable_Abstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
