<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../Biriani_HTTPTransaction.php';

/**
 * Test class for Biriani_HTTPTransaction.
 * Generated by PHPUnit on 2012-02-04 at 04:23:32.
 */
class Biriani_HTTPTransactionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Biriani_HTTPTransaction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Biriani_HTTPTransaction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGet_url().
     */
    public function testGet_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSet_url().
     */
    public function testSet_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_header().
     */
    public function testGet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSet_header().
     */
    public function testSet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_content().
     */
    public function testGet_content() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSet_content().
     */
    public function testSet_content() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_all_headers().
     */
    public function testGet_all_headers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testClear_headers().
     */
    public function testClear_headers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
