<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../FeedBiriani.php';

/**
 * Test class for FeedBiriani.
 * Generated by PHPUnit on 2012-02-04 at 04:32:09.
 */
class FeedBirianiTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FeedBiriani
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FeedBiriani;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testCan_extract().
     */
    public function testCan_extract() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExtract().
     */
    public function testExtract() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
